steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/webcalc-ui', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/webcalc-ui']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'webcalc-ui',
        '--image', 'gcr.io/$PROJECT_ID/webcalc-ui',
        '--platform', 'managed',
        '--region', 'australia-southeast1',
        '--allow-unauthenticated'
      ]

images:
  - gcr.io/$PROJECT_ID/webcalc-ui